config/routes.rb
Rails.application.routes.draw do
  # Devise route setup
  devise_for :users, controllers: {
	registrations: 'users/registrations'
}
  # Setting the root route
  root to: "static_pages#welcome"

  # Generate default routes for Users
  resources :users

  # Generate nested routes for Cities and Posts
  resources :cities do
    resources :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :posts
  has_many :users, through: :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :city

  validates :content, presence: true
  validates :title, length: {in: 1..200}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :cities, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @posts = @city.posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Define routes that require authentication
  before_action :authenticate_user!, only: [:new, :create]

  # Define routes that current user must be account owner else redirect
  before_action :redirect_unless_owner, only: [:edit, :update, :destroy]
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @city = @post.city
  end

  def new
    @city = City.find(params[:city_id])
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @city = @post.city

    # If post.save fails, error messages will be automatically populated on the post object
    if @post.save
      redirect_to city_post_path(@city, @post), notice: 'Post created successfully.'
    else
      # Rerender the view with error message(s) and auto populate fields
      flash[:alert] = @post.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @city = @post.city
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to city_post_path(post.city, post)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end

  private

  def post_params
    # Only allow expected parameters
    params.require(:post)
      .permit(:title, :content)
      .merge(user_id: current_user.id, city_id: params[:city_id])
  end

  def redirect_unless_owner
    # Protect against unauthorized changes
    post = Post.find(params[:id])
    if (current_user.id != post.user.id)
      redirect_to root_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
    
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :current_city])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :current_city, :image_url])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/delete.html.erb
<h1>Cities#delete</h1>
<p>Find me in app/views/cities/delete.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities</h1>
<% @cities.each do |city| %>
  <div class="jumbotron">
    <img class="img-responsive img-rounded" src="<%= city.image_url %>" alt="">
    <h2 class="text-center"><%= link_to city.name, city_path(city) %></h2>
  </div>
<% end %>

app/views/cities/show.html.erb
<div class="jumbotron">
  <h1 class="text-center"><%= @city.name %></h1>
</div>
<% if @posts.empty? %>
  <h3>There are no tips for <%= @city.name %>. <%= link_to "Add tip", new_city_post_path(@city) %>?</h3>
<% else %>
  <% @posts.reverse_each do |post| %>
  <div class="jumbotron">
    <div class="row">
      <div class="col-sm-3 hidden-xs">
        <img src="<%= post.user.image_url %>" class="img-responsive img-rounded portrait" alt="">
      </div>
      <div class="col-sm-9">
        <h2>
          <%= link_to post.title, city_post_path(post.city, post) %> <br>
          <small>by <%=link_to post.user.full_name.blank? ? "Anonymous user" : post.user.full_name, user_path(post.user) %>, <%= time_ago_in_words(post.created_at)%> ago.</small>
        </h2>
        <p><%= truncate(post.content, length: 1000) %></p>
      </div>
    </div>
  </div>
  <% end %>
  <h1 class="text-center">Have a tip? <%= link_to "Add it", new_city_post_path(@city)%>!</h1>
<% end %>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vagabond</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/cities"><%= image_tag "city-tips-logo.png", class: "navbar-brand" %></a>
          <% if @city %>
            <p class="navbar-text"><%= link_to @city.name, city_path(@city.id) %></p>
          <% end %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? && @city %>
              <li><%= link_to "New Post", new_city_post_path(@city) %></li>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
            <% elsif user_signed_in? %>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
      <% if @city %>
        <img class="img-responsive banner-img" src="<%=@city.image_url%>" alt="">
      <% else %>
        <img class="img-responsive banner-img" src="http://www.layoverguide.com/wp-content/uploads/2009/03/Miami-city-skyline.jpg" alt="">
      <% end %>
      <div class="container">
        <% if notice %>
        	<p class="alert alert-success message"><%= notice %></p>
        <% end %>
        <% if alert %>
        	<p class="alert alert-danger message"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted"><small>by: Harry Karambizi, Neil Morris, Peter Colella, and Ray Meibaum</small></p>
      </div>
    </footer>
    <!-- <script src="https://use.fontawesome.com/888a262cf1.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= form_for [@city, @post] do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
<%= f.label :content %>
<%= f.text_area :content, class: "form-control" %>
</div>

<%= f.submit class: "btn btn-success"%>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= form_for [@city, @post] do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
<%= f.label :content %>
<%= f.text_area :content, class: "form-control" %>
</div>

<%= f.submit class: "btn btn-success"%>
<% end %>

app/views/posts/show.html.erb
<div class="jumbotron">
  <h1 class="text-center"><%= @post.title %> <br><small> <%= link_to @post.city.name, city_path(@post.city) %></small></h1>
</div>
<div class="jumbotron">
  <div class="row">
    <div class="col-sm-3">
      <img class="img-responsive img-rounded hidden-xs" src="<%= @user.image_url %>" alt="">
    </div>
    <div class="col-sm-9">
      <p><%= @post.content %> <br>
      <span class="pull-right text-muted">by <%= link_to @user.full_name.blank? ? "Anonymous user" : @user.full_name, user_path(@user) %>, <%= time_ago_in_words(@post.created_at)%> ago.</span>
      </p>
    </div>
  </div>
</div>

app/views/static_pages/welcome.html.erb
<h1>Welcome to City Tips</h1>
<p class="lead">A site for creating and viewing tips for your favorite cities.</p>
<strong>Feel free to:</strong>
<ul>
  <% if !current_user %>
    <li><%= link_to "log in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %> </li>
  <% end%>
  <li>view the <%= link_to "available cities", cities_path %></li>
</ul>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <img class="img-responsive img-rounded hidden-xs" src="<%= @user.image_url %>" alt="">
    <h3><%= @user.full_name.blank? ? "Anonymous user" : @user.full_name  %></h3>
    <h3>Joined: <%= @user.created_at.strftime("%x") %></h3>
    <% if !@user.current_city.blank? %>
      <h3>Current City: <%= @user.current_city %></h3>
    <% end %>
    <% if current_user == @user %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-warning"%>
    <% end %>
  </div>
  <div class="col-sm-8">
    <% if @posts.empty? %>
      <h1><%= @user.full_name.blank? ? "Anonymous user" : @user.full_name  %> has posted no tips.</h1>
    <% else %>
      <% @posts.reverse_each do |post| %>
        <div class="post">
          <h1>
            <%= link_to post.title, city_post_path(post.city, post) %> <br>
            <small>posted in <%= link_to post.city.name, city_path(post.city) %> <%= time_ago_in_words(post.created_at)%> ago</small>
          </h1>

          <p><%= truncate(post.content, length: 1000) %></p>
          <% if current_user == post.user %>
            <%= link_to icon('pencil', class: "fa-3x"), edit_city_post_path(post.city, post) %>
            <%= link_to icon('trash-o', class: "fa-3x"), city_post_path(post.city, post), :data => {:confirm => "Are you sure you want to delete #{post.title}?"}, :method => 'delete' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>